### ISSUE TITLE
Create `check_tbl_values_col` function

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubValidations#19]
A number of checks required, some according to output type.

- [x] `check_tbl_value_col`: Some of the variability in checks is captured by the limitations of the schema so a check against the `tasks` config file will suffice. This includes:
  - mean/median/quantile/sample(current implementation): 
    - type: can be coerced to type (req)
    - min: optional
    - max: optional
  - cdf/pmf:
    - type: can be coerced to type (req)
    - min: 0 (req)
    - max: 1 (req)

### CDF/quantile
- [x] `check_tbl_value_col_ascending`: for each individual prediction, entries in value must be non-decreasing as output_type_id increase.

### pmf
- [x] `check_tbl_value_col_sum1` values must add up to 1

**Comment by annakrystalli** [comment]
@LucieContamin & @elray1 , can you have a quick look at the manual checks listed above and confirm I've not missed or got sth wrong?

**Comment by LucieContamin** [comment]
I have a question about the "can be coerced to type". For type integer, we can coerced float to integer in R without any issue but we might want the validation to still return an error. Will the validation will take that behavior into account?

**Comment by elray1** [comment]
I can't think of anything else

**Comment by annakrystalli** [comment]
> I have a question about the "can be coerced to type". For type integer, we can coerced float to integer in R without any issue but we might want the validation to still return an error. Will the validation will take that behavior into account?

So the reason we need to check this is because values for multiple output types are stacked in a single column and coerced to the lowest common denominator. So if we have two type IDs, one which accepts integers and the other double (number in json), in the column they would all be stored as double, but that shouldn't trigger a failure as there is no other way to mix those data types in a single column. 

The actual check splits the submission file into separate output types (and in fact modleing tasks too to match data to exactly to the correct config section) and checks that each chunk can be coerced to the data type in the config. It's the only way really to test against the `value` objects in the config.  What I mainly envisage it catching though stray characters etc.

Does that make more sense?

**Comment by annakrystalli** [comment]
Yes! That makes total sense. Sorry for the confusion. And yes you are right, that should totally fail. Will implement.

**Comment by annakrystalli** [comment]
Fixed in e3a65dea9a72e534ba4da764eaaf4277fa916cca.

Also helped detect error in hubUtils flusight example hub files! e.g https://github.com/Infectious-Disease-Modeling-Hubs/hubUtils/blob/main/inst/testhubs/flusight/forecasts/hub-ensemble/2023-04-24-hub-ensemble.csv#L1-L4
