### ISSUE TITLE
Create `opt_check_tbl_counts_lt_popn()` fn

### ISSUE THREAD

**Issue by annakrystalli** [Infectious-Disease-Modeling-Hubs/hubValidations#33]
Predictions are not greater than population size

For flusight, can look up population values from here: https://github.com/cdcepi/FluSight-forecast-hub/blob/main/auxiliary-data/locations.csv

Arguments to this validation function:
- Where to find popn file
- What column in this file has population values
- What column in this file has location values
- Which targets need to be checked? (Need to somehow specify which values (i.e., which rows) need to be checked (combination of task ids and output types?)

Logic:
- Subset to rows that need to be checked
- Join `locations.csv` and submission file on the specified column (in this example, location)
- If any `NA`s in popn values, throw error (i. e. Check throws error if submission file contains locations which do not match locations in population file.)
- Check that `value` less than `population` in all rows

**Comment by annakrystalli** [comment]
@elray1 @LucieContamin @eahowerton Do you use this check and if so, how do you all feel about `locations.csv` as the default name for the file?

**Comment by LucieContamin** [comment]
We are using this check on the US SMH, I am ok with the default name of the file. We should just prepare some documentation to go with the file.
