### ISSUE TITLE
hubValidations quantile check error if the quantiles are not ordered

### ISSUE THREAD

**Issue by M-7th** [Infectious-Disease-Modeling-Hubs/hubValidations#70]
Working on the https://respicast.ecdc.europa.eu/ platform we noticed a feature of the validations package that modelers don't find desirable.
When checking that the values for quantiles are decreasing, the validations give the following error if the quantiles are not ordered in the input file:
`! 2024-01-10-ISI-FluABCaster.csv: Values in 'value' column are not non-decreasing as output_type_ids increase for all unique task ID value/output type combinations of quantile or cdf output types. See `error_tbl` attribute for details.`

Once the quantiles are ordered the validation step is passed without errors:
`✔ 2024-01-10-ISI-FluABCaster.csv: Values in 'value' column are non-decreasing as output_type_ids increase for all unique task ID value/output type combinations of quantile or cdf output types.`

Is there a rationale for this? Would it be possible to perform the check without requiring that the records are written in the file ordered by quantile?

Attached you can find the ordered and unordered csv files used to reproduce this issue.

Many thanks for your kind assistance
Paolo

[2024-01-10-ISI-FluABCaster_not_ordered.csv](https://github.com/Infectious-Disease-Modeling-Hubs/hubValidations/files/13917777/2024-01-10-ISI-FluABCaster_not_ordered.csv)
[2024-01-10-ISI-FluABCaster_ordered.csv](https://github.com/Infectious-Disease-Modeling-Hubs/hubValidations/files/13917778/2024-01-10-ISI-FluABCaster_ordered.csv)

**Comment by annakrystalli** [comment]
Thanks for reporting @M-7th ! 

This was indeed a bug and is now fix in eac30361b3f4d09096d320182aa3a4ac35d9b861 as part of #67 . Should be merged in soon !

**Comment by M-7th** [comment]
Many thanks @annakrystalli  for your support
